# System: keymap, external toolchains, network, telemetry, extension
# capabilities, settings profiles, and channel/platform overrides.
{
  # ── Keymap ───────────────────────────────────────────────────────────────
  # "VSCode" | "Atom" | "JetBrains" | "None" | "SublimeText" | "TextMate"
  base_keymap = "VSCode";

  vim_mode = false;
  # Enabling helix mode also enables vim mode.
  helix_mode = false;

  vim = {
    default_mode = "normal";
    toggle_relative_line_numbers = false;
    use_system_clipboard = "always";
    use_smartcase_find = false;
    use_regex_search = true;
    gdefault = false;
    highlight_on_yank_duration = 200;
    custom_digraphs = {};
    show_edit_predictions_in_normal_mode = false;
    # "block" | "bar" | "underline" | "hollow" | "inherit"
    cursor_shape = {
      normal = "block";
      replace = "underline";
      visual = "block";
      insert = "inherit";
    };
  };

  which_key = {
    enabled = true;
    delay_ms = 1000;
  };

  # Command palette aliases, e.g. W = "workspace::Save";
  command_aliases = {};

  # ── External toolchains ──────────────────────────────────────────────────
  # Node used to install language servers and Copilot; changes need a restart.
  node = {
    # true forces Zed to download and use its own Node.
    ignore_system_version = false;
    # With path but no npm_path, npm is assumed at ${path}/../npm.
    path = null;
    npm_path = null;
  };

  # "direct" (direnv export json) | "shell_hook" | "disabled"
  load_direnv = "direct";

  # ── Network ──────────────────────────────────────────────────────────────
  # Scheme selects the protocol: http/https/socks4/socks4a/socks5/socks5h.
  # Empty falls back to the environment; exceptions go in no_proxy.
  proxy = "";

  # Overridden by the ZED_SERVER_URL environment variable.
  server_url = "https://zed.dev";

  # e.g. { host = "example-box"; port = 22; username = "test";
  #        projects = [ { paths = ["/home/user/code"]; } ]; }
  ssh_connections = [];

  read_ssh_config = true;

  # ── Telemetry and updates ────────────────────────────────────────────────
  telemetry = {
    diagnostics = false;
    metrics = false;
    # Allows requests to Anthropic models without zero data retention.
    anthropic_retention = false;
  };

  # Updates are handled by the Homebrew cask.
  auto_update = false;

  # ── Extensions ───────────────────────────────────────────────────────────
  # auto_install_extensions is generated by programs.zed-editor.extensions and
  # overrides anything set here; edit ../extensions.nix instead.
  # auto_install_extensions = {
  #   html = true;
  # };

  # Capabilities granted to extensions. Kinds: process:exec, download_file,
  # npm:install.
  granted_extension_capabilities = [
    {
      kind = "process:exec";
      command = "*";
      args = ["**"];
    }
    {
      kind = "download_file";
      host = "*";
      path = ["**"];
    }
    {
      kind = "npm:install";
      package = "@biomejs/biome";
    }
    {
      kind = "npm:install";
      package = "dockerfile-language-server-nodejs";
    }
    {
      kind = "npm:install";
      package = "@microsoft/compose-language-service";
    }
    {
      kind = "npm:install";
      package = "graphql-language-service-cli";
    }
    {
      kind = "npm:install";
      package = "@olrtg/emmet-language-server";
    }
  ];

  # ── Logging ──────────────────────────────────────────────────────────────
  # Log scope to level, e.g. { client = "warn"; }
  log = {};

  journal = {
    path = "~";
    # "hour12" | "hour24"
    hour_format = "hour12";
  };

  instrumentation = {
    # Opened via "zed: open performance profiler"; increases memory usage.
    performance_profiler = {
      enabled = false;
    };
  };

  # ── Settings profiles ────────────────────────────────────────────────────
  # Switched via "settings profile selector: toggle".
  # base = "user" layers on top of these settings, "default" ignores them.
  # e.g. Presenting = { base = "default"; settings = { buffer_font_size = 20; }; };
  profiles = {};

  # ── Release channel and platform overrides ───────────────────────────────
  preview = {};

  nightly = {
    instrumentation = {
      performance_profiler = {
        enabled = true;
      };
    };
  };

  stable = {};

  dev = {
    instrumentation = {
      performance_profiler = {
        enabled = true;
      };
    };
  };

  linux = {};
  macos = {};
  windows = {};
}
